### ISSUE TITLE
please be quiet

### ISSUE THREAD

**Issue by koriege** [mxmlnkn/rapidgzip#25]
Hi,

stunned by the performance, I'd like to use rapidgzip (I am on v 0.10.3) as drop-in replacement in my scripts, but despite of using the `-q` switch, the efficiency message still appears ("Decompressed in total xxx B in xxx s -> xxx MB/s"). May I suggest to completely silence rapidgzip (which would also overcome the use of `-q`, thus being a real drop-in replacement) and let e.g. non-error messages popping up by allowing different levels of verbosity?

**Comment by mxmlnkn** [comment]
Sounds reasonable. I'd say, that this is more of a leftover from the (ongoing) development and performance benchmarking. I might even include the silencing in v0.10.4, which I hopefully get released by next week.
