### ISSUE TITLE
suggestion: add handler for SIGPIPE

### ISSUE THREAD

**Issue by koriege** [mxmlnkn/rapidgzip#32]
Hi,

I am using rapidgzip as a drop-in replacement for gunzip, pigz respectively. 
Whereas the latter tools exit with 141 upon SIGPIPE without further messages, rapidgzip exit code is 1 and prints an error stack trace.
May I suggest to silence rapidgzip and exit with 141 as well?

Example:
`seq 1 10000 | gzip -c | gzip -d | head; echo ${PIPESTATUS[*]} # 0 0 141 0`
vs
`seq 1 10000 | gzip -c | rapidgzip -d | head; echo ${PIPESTATUS[*]} # 0 0 1 0`

**Comment by koriege** [comment]
Oh sorry, my fault. I was still on 10.4
v0.11.0 and v0.11.2 are working as ~ expected (exit code 0)

**Comment by mxmlnkn** [comment]
Ah ok. The error on 0.10.4 is `ValueError: This class heavily relies on seeking and won't work with unseekable files!`. Support for non-seekable files is a new feature in 0.11.0.

**Comment by koriege** [comment]
sorry again for beeing unprecise, I tested multiple commands.
beeing on v011.1, I get the following trace with an exit code 0
```
seq 1 100000| gzip -kc > foo.gz; rapidgzip -kcd foo.gz | head -1
1
error: 32
Traceback (most recent call last):
  File "/home/lakatos/kriege/programs/conda/envs/test/bin/rapidgzip", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "rapidgzip.pyx", line 665, in rapidgzip.cli
RuntimeError: Failed to write to pipe
```

**Comment by mxmlnkn** [comment]
Ok, it seems to work just fine. You could pipe stderr to /dev/null to avoid the traceback output but I guess you don't want to do that because it is not necessary for gzip? I probably can catch that exception and suppress the traceback and it should work just fine.

**Comment by koriege** [comment]
this would be great. I am also wondering, why this trace does not occur for smaller files (seq to 10k instead of 100k)
`seq 1 10000 | gzip -kc > foo.gz; rapidgzip -kcd foo.gz | head -1`

**Comment by mxmlnkn** [comment]
> I probably can catch that exception and suppress the traceback and it should work just fine.

There are some conceptual problems, though, when it comes to combined command-line actions. For example, you can do: `src/tools/rapidgzip -kcd --export-index index --count foo.gz> /dev/null | head` and it probably should still generate the full index and maybe even return the correct count on stderr. However, without any of these additional options, we would want to stop decoding as soon as the output stream end has been encountered. Therefore, it seems like a simple try-catch will not work, and instead, some kind of flag is necessary.

> I am also wondering, why this trace does not occur for smaller files (seq to 10k instead of 100k) `seq 1 10000 | gzip -kc > foo.gz; rapidgzip -kcd foo.gz | head -1`

Interesting question. This is because I'm using vmsplice, which is kind of asynchronous. The first call will work just fine, while the second or third call, depending on how much time has passed, will return the broken pipe error. On my system `seq 1 14117` works but `seq 1 14118` yields the exception.

```console
> seq 1 14117 | gzip -kc > foo.gz; python3 -u -c 'import rapidgzip; rapidgzip.cli()' -kcd foo.gz | head -1 > /dev/null; echo ${PIPESTATUS[*]}
[writeAll] outputFileDescriptor: 1, dataToWriteSize: 73596
[writeAllSplice] outputFileDescriptor: 1, buffersToWrite count: 1
[SpliceVault::splice] buffersToWrite count: 1
[writeAllSpliceUnsafe] vmsplice( 1, i=0, segmentCount=1)
[writeAllSpliceUnsafe] nBytesWritten: 65408)
[writeAllSpliceUnsafe] Write remaining iovec. Currently at i=0 out of 1, nBytesWritten: 65408
[writeAllSpliceUnsafe] vmsplice( 1, dataToSplice.iov_len:8188)
[writeAllSpliceUnsafe] nBytesWritten:8188
0 0
```

```console
> seq 1 14118 | gzip -kc > foo.gz; python3 -u -c 'import rapidgzip; rapidgzip.cli()' -kcd foo.gz | head -1 > /dev/null; echo ${PIPESTATUS[*]}
[writeAll] outputFileDescriptor: 1, dataToWriteSize: 73602
[writeAllSplice] outputFileDescriptor: 1, buffersToWrite count: 1
[SpliceVault::splice] buffersToWrite count: 1
[writeAllSpliceUnsafe] vmsplice( 1, i=0, segmentCount=1)
[writeAllSpliceUnsafe] nBytesWritten: 65408)
[writeAllSpliceUnsafe] Write remaining iovec. Currently at i=0 out of 1, nBytesWritten: 65408
[writeAllSpliceUnsafe] vmsplice( 1, dataToSplice.iov_len:8194)
[writeAllSpliceUnsafe] nBytesWritten:8192
[writeAllSpliceUnsafe] vmsplice( 1, dataToSplice.iov_len:2)
[writeAllSpliceUnsafe] nBytesWritten:-1
error: 32
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "rapidgzip.pyx", line 707, in rapidgzip.cli
RuntimeError: Failed to write to pipe
1 0
```

It looks a bit different when calling rapidgzip built with CMake (without the Python layer):

```console
> seq 1 14118 | gzip -kc > foo.gz; src/tools/rapidgzip -kcd foo.gz | head -1 > /dev/null; echo ${PIPESTATUS[*]}
[writeAll] outputFileDescriptor: 1, dataToWriteSize: 73602
[writeAllSplice] outputFileDescriptor: 1, buffersToWrite count: 1
[SpliceVault::splice] buffersToWrite count: 1
[writeAllSpliceUnsafe] vmsplice( 1, i=0, segmentCount=1)
[writeAllSpliceUnsafe] nBytesWritten: 65408
[writeAllSpliceUnsafe] Write remaining iovec. Currently at i=0 out of 1, remaining bytes to write: 65408
[writeAllSpliceUnsafe] vmsplice( 1, dataToSplice.iov_len:8194)
[writeAllSpliceUnsafe] nBytesWritten:8192
[writeAllSpliceUnsafe] vmsplice( 1, dataToSplice.iov_len:2)
141 0
```

**Comment by koriege** [comment]
> For example, you can do: `src/tools/rapidgzip -kcd --export-index index --count foo.gz> /dev/null | head` and it probably should still generate the full index and maybe even return the correct count on stderr.

I don't get your point here. This command will always generate the full index and terminates without receiving any signal by `head`, because `head` will never get any stdin. On the other hand, when the user is not redirecting to `/dev/null`, and `head` is going to kill the rapidgzip process, for sure also the index will be and should be corrupted as a result of what the user did.

> The first call will work just fine, while the second or third call, depending on how much time has passed, will return the broken pipe error.

I see, but can't you simply exit the python main upon catching BokenPipeError and KeyboardInterrupt (SIGINT, or ctr+c)

**Comment by mxmlnkn** [comment]
I have pushed a commit. You can try it out with:

```
python3 -m pip install --force-reinstall 'git+https://github.com/mxmlnkn/indexed_bzip2.git@master#egginfo=rapidgzip&subdirectory=python/rapidgzip'
```

**Comment by koriege** [comment]
works like charm. thank you.
> the exit code 141 is very likely shell-dependent
Actually not. As far as I know, the kernel sends SIGPIPE to the process which continues writing to a buffer, for which no readers exist any more. My guess is, that `vmsplice` receives the SIGPIPE and terminates by throwing `EPIPE` error, which bubbles up in the Python code and has to be catch there accordingly. Thought, I am not a Python developer..
